### ISSUE TITLE
FATAL ERROR: settings_t::rdwr() - Too many (26980) city roads!

### ISSUE THREAD

**Issue by steffen123** [jamespetts/simutrans-experimental#43]
Hi,
as promised, here is the report about it crashing whilst loading an old game. The end of the shell output:
Show banner ... 
Running world, pause=0, fast forward=0 ... 
World destroyed.
FATAL ERROR: settings_t::rdwr() - Too many (26980) city roads!
Aborting program execution ...

For help with this error or to file a bug report please see the Simutrans forum at
http://forum.simutrans.com
Aborted

If this is expected behaviour due to a new limitation just let me know and I'll forget about the savegame, not a problem. As always, happy to bisect and I'll email you the savegame.

**Comment by steffen123** [comment]
Almost forgot, I get the error with commit 40954d40d0371aed6ea375f66f8423be9de4efb4

**Comment by jamespetts** [comment]
Steffen,

the format of the saved game has changed since your older games were 
saved; you need to use a special procedure to rescue your old saved 
games by defining SPECIAL_RESCUE_12_[x] where [x] is a number from 2 - 
6, as well as SPECIAL_RESCUE_12, loading your games, saving them, then 
re-compiling without those symbols defined to load your games again and 
continue running as normal. However, which of those symbols that you 
need to define will depend on the precise version that you used to save 
the games.

This is all documented in the various Git commit comments, so you should 
be able to work this out from there. I have modified the saved game 
versioning system since this to prevent this from needing to happen 
again, but it is not retrospective, so you still need to use the 
SPECIAL_RESCUE procedure for these older saved games;

James.

**Comment by steffen123** [comment]
Ok, thanks for the info.
